testname: Rhythmic Complexity Perceptive Test
testId: Rhythmic_Complexity_Test
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:

    - type: generic
      id: first_page
      name: "Welcome and thank you for partecipating!"
      content: >
              Welcome to this perceptive test, which is part of a research for a Music Engineering MSc thesis at Politecnico di Milano. <br />
              The test is intended to investigate the idea of rhythmic complexity, as it is one of the most interesting and determinant properties when it comes to describe a rhythm, which is itself one of the main aspects involved in music. 
              Of course, listening to music is a subjective experience, so it is very hard to find formal definitions of the aspects involved in this phenomena. That's why perceptive tests are so important. 
              Moreover, being the perceived rhythmic complexity one of the most challenging-to-define features for a music track, a definition of it would constitute a big step forward in a Music Information Retrieval context. 
              Also, with such a definition, many unexplored applications would become accessible, both in the analytical and generative sense. <br />
              <br /> 

              So, first of all, thank you for your collaboration. Your contribute is very important. <br />
              

              Following, the structure of the test is described. <br />
              <br /> 
              
              You are going to listen to some rhythmic patterns, and for each of them you will be asked to express a rating to tell how complex you find them from a rhythmic point of view. <br />
              Make sure not to listen to all rhythms many times and get your ears tired. If you feel like you need a pause, feel free to take it. Your judgement is expected to be lucid. <br />
              Also, please, take the test in a quiet place, or use your headphones. Stay focused, it will not take much time. <br />
              The test is intended to last a maximum of 15 min. <br />
              <br /> 

              Thanks again for you collaboration. <br />
              <br />

              In the next page you are going to listen to some examples with varying levels of complexity.
  


    - type: generic
      id: training_1
      name: Training No.1
      content: >
               In the following pages there will be many rhythmic patterns of varying complexity. <br/>
               To let you have a preliminary idea of the complexity gradient present in the test, 
               here below some examples that you are going to listen again in the real test are reported. <br/>
               Among these examples there are very easy patterns from a rhythmic point of view, as well as really complex ones, and compromises. <br/><br/>
               <audio controls><source src='configs/resources/audio/patterns/dataset_001/page_004/3 - Costante.mp3' type='audio/mp3'></audio><br/>
               <audio controls><source src='configs/resources/audio/patterns/dataset_001/page_003/14 - Random.mp3' type='audio/mp3'></audio><br/>
               <audio controls><source src='configs/resources/audio/patterns/dataset_001/page_004/13 - Random.mp3' type='audio/mp3'></audio><br/>
               <audio controls><source src='configs/resources/audio/patterns/dataset_001/page_001/2 - Costante.mp3' type='audio/mp3'></audio><br/>
               <audio controls><source src='configs/resources/audio/patterns/dataset_003/page_004/3 - Gerarchia.mp3' type='audio/mp3'></audio><br/>
               <audio controls><source src='configs/resources/audio/patterns/dataset_002/page_003/29 - Human.mp3' type='audio/mp3'></audio><br/>
               <audio controls><source src='configs/resources/audio/patterns/dataset_001/page_001/19 - Gerarchia.mp3' type='audio/mp3'></audio><br/>


    

      # PAGE 1 OF RATING
    - type: likert_multi_stimulus
      id: Rating_page_1
      name: Rate Rhythm Complexity (1st of 4)
      content: Hear below you are going to find some rhythmic patterns, for each of them rate how much rhythmic complexity you perceive
      random: True
      # mustRate: True
      # mustPlayback: ended
      stimuli:
          Rhtyhm_112C: configs/resources/audio/patterns/dataset_001/page_001/2 - Costante.mp3
          Rhtyhm_113H: configs/resources/audio/patterns/dataset_001/page_001/3 - Human.mp3
          Rhtyhm_114G: configs/resources/audio/patterns/dataset_001/page_001/4 - Gerarchia.mp3
          Rhtyhm_116C: configs/resources/audio/patterns/dataset_001/page_001/6 - Costante.mp3
          Rhtyhm_116R: configs/resources/audio/patterns/dataset_001/page_001/6 - Random.mp3
          Rhtyhm_117R: configs/resources/audio/patterns/dataset_001/page_001/7 - Random.mp3
          Rhtyhm_118G: configs/resources/audio/patterns/dataset_001/page_001/8 - Gerarchia.mp3
          Rhtyhm_119G: configs/resources/audio/patterns/dataset_001/page_001/19 - Gerarchia.mp3
          Rhtyhm_1125C: configs/resources/audio/patterns/dataset_001/page_001/25 - Costante.mp3
          Rhtyhm_1127R: configs/resources/audio/patterns/dataset_001/page_001/27 - Random.mp3
          
      response:
        - value: Not complex at all
          label: Not complex at all
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Not that complex
          label: Not that complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Medium complexity
          label: Medium complexity
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Complex
          label: Complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png  
        - value: Very complex
          label: Very complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png  

  
      # PAGE 2 OF RATINGS
    - type: likert_multi_stimulus
      id: Rating_page_2
      name: Rate Rhythm Complexity (2nd of 4)
      content: Hear below you are going to find some rhythmic patterns, for each of them rate how much rhythmic complexity you perceive
      random: True
      # mustRate: True
      # mustPlayback: ended
      stimuli:
          Rhtyhm_125C: configs/resources/audio/patterns/dataset_001/page_002/5 - Costante.mp3
          Rhtyhm_125H: configs/resources/audio/patterns/dataset_001/page_002/5 - Human.mp3
          Rhtyhm_1210C: configs/resources/audio/patterns/dataset_001/page_002/10 - Costante.mp3
          Rhtyhm_1212G: configs/resources/audio/patterns/dataset_001/page_002/12 - Gerarchia.mp3
          Rhtyhm_1215R: configs/resources/audio/patterns/dataset_001/page_002/15 - Random.mp3
          Rhtyhm_1216R: configs/resources/audio/patterns/dataset_001/page_002/16 - Random.mp3
          Rhtyhm_1218C: configs/resources/audio/patterns/dataset_001/page_002/18 - Costante.mp3
          Rhtyhm_1219H: configs/resources/audio/patterns/dataset_001/page_002/19 - Human.mp3
          Rhtyhm_1223H: configs/resources/audio/patterns/dataset_001/page_002/23 - Human.mp3
          Rhtyhm_1230C: configs/resources/audio/patterns/dataset_001/page_002/30 - Costante.mp3
          
      response:
        - value: Not complex at all
          label: Not complex at all
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Not that complex
          label: Not that complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Medium complexity
          label: Medium complexity
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Complex
          label: Complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png  
        - value: Very complex
          label: Very complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png  



      # PAGE 3 OF RATINGS
    - type: likert_multi_stimulus
      id: Rating_page_3
      name: Rate Rhythm Complexity (3rd of 4)
      content: Hear below you are going to find some rhythmic patterns, for each of them rate how much rhythmic complexity you perceive
      random: True
      # mustRate: True
      # mustPlayback: ended
      stimuli:
          Rhtyhm_132G: configs/resources/audio/patterns/dataset_001/page_003/2 - Gerarchia.mp3
          Rhtyhm_1310H: configs/resources/audio/patterns/dataset_001/page_003/10 - Human.mp3
          Rhtyhm_1311G: configs/resources/audio/patterns/dataset_001/page_003/11 - Gerarchia.mp3
          Rhtyhm_1312R: configs/resources/audio/patterns/dataset_001/page_003/12 - Random.mp3
          Rhtyhm_1313H: configs/resources/audio/patterns/dataset_001/page_003/13 - Human.mp3
          Rhtyhm_1314R: configs/resources/audio/patterns/dataset_001/page_003/14 - Random.mp3
          Rhtyhm_1316G: configs/resources/audio/patterns/dataset_001/page_003/16 - Gerarchia.mp3
          Rhtyhm_1317H: configs/resources/audio/patterns/dataset_001/page_003/17 - Human.mp3
          Rhtyhm_1321G: configs/resources/audio/patterns/dataset_001/page_003/21 - Gerarchia.mp3
          Rhtyhm_1325G: configs/resources/audio/patterns/dataset_001/page_003/25 - Gerarchia.mp3
          
      response:
        - value: Not complex at all
          label: Not complex at all
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Not that complex
          label: Not that complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Medium complexity
          label: Medium complexity
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Complex
          label: Complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png  
        - value: Very complex
          label: Very complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png  
         

  
      # PAGE 4 OF RATINGS
    - type: likert_multi_stimulus
      id: Rating_page_4
      name: Rate Rhythm Complexity (4th of 4)
      content: Hear below you are going to find some rhythmic patterns, for each of them rate how much rhythmic complexity you perceive
      random: True
      # mustRate: True
      # mustPlayback: ended
      stimuli:
          Rhythm_143C: configs/resources/audio/patterns/dataset_001/page_004/3 - Costante.mp3
          Rhythm_1413R: configs/resources/audio/patterns/dataset_001/page_004/13 - Random.mp3
          Rhythm_1416C: configs/resources/audio/patterns/dataset_001/page_004/16 - Costante.mp3
          Rhythm_1417C: configs/resources/audio/patterns/dataset_001/page_004/17 - Costante.mp3
          Rhythm_1418H: configs/resources/audio/patterns/dataset_001/page_004/18 - Human.mp3
          Rhythm_1424G: configs/resources/audio/patterns/dataset_001/page_004/24 - Gerarchia.mp3
          Rhythm_1427C: configs/resources/audio/patterns/dataset_001/page_004/27 - Costante.mp3
          Rhythm_1427G: configs/resources/audio/patterns/dataset_001/page_004/27 - Gerarchia.mp3
          Rhythm_1429R: configs/resources/audio/patterns/dataset_001/page_004/29 - Random.mp3
          Rhythm_1430G: configs/resources/audio/patterns/dataset_001/page_004/30 - Gerarchia.mp3
          
      response:
        - value: Not complex at all
          label: Not complex at all
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Not that complex
          label: Not that complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Medium complexity
          label: Medium complexity
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: Complex
          label: Complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png  
        - value: Very complex
          label: Very complex
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png  
         

    - type: finish
      name: Thank you
      content: Thank you for attending! <br/> <br/>
      popupContent: Your results were sent. Goodbye and have a nice day   
      showResults: true
      writeResults: true
      questionnaire:
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
          - type: number 
            label: Years of formal music training
            name: years_training
            min: 0
            max: 100
            default: 5
          - type: text
            label: Country
            name: country
          - type: long_text
            label: Feedback
            name: feedback
            optional: true
